### PR TITLE
Support swift 5

### PR DESCRIPTION
**Pull request by eduardorfreitas93**
- Support swift 5
- .podspec version 0.0.7

### CODE REVIEW

**Comment by milansusnjar** [comment]
This helps a lot. Should be published for 0.x version users.

**Comment by mathieumg** [comment]
> Should be published for 0.x version users.

Would love for that to happen as well!

**Comment by serjbord** [comment]
is any chance to get this published?

**Comment by prscX** [comment]
Thanks @eduardorfreitas93 for the PR and Effort.

I have merged the same. Considering `pod` support in >= RN61, I am planning to push this with `V1.*`.


Thanks
</ Pranav >

**Comment by prscX** [comment]
Thanks @eduardorfreitas93 for the Effort and PR.

Could you please take latest pull and resolve the conflicts. Post that we can merge the PR.

Thanks
</ Pranav >

**Comment by prscX** [comment]
@eduardorfreitas93: Closing this PR since I have pulled all the required Swift 5 support changes in latest release.

Thanks for your Effort and PR.

Thanks
</ Pranav >

**Pull request closed without merging**
