### PR TITLE
Fix typing issues - Typescript check

### PR DESCRIPTION
**Pull request by DonovanDeSmedt**
Added correct typing to index.tsx to fix TS error TS7006: Parameter 'resultCode' and Parameter 'imagePath' implicitly has an 'any' type

### CODE REVIEW

**Comment by MakhouT** [comment]
Awesome well done! Thank you! @prscX Can you please merge it?

**Comment by prscX** [comment]
Thanks @DonovanDeSmedt for the Effort and PR.

I have merged the PR. Will push the release.

Thanks

**Comment by stu-dev** [comment]
Any news on when this will be released?

**Comment by prscX** [comment]
@stu-dev: I have pushed the release.

@DonovanDeSmedt: Thanks for the effort.

[V1.0.9](https://github.com/prscX/react-native-photo-editor/releases/tag/v1.0.9)

Thanks
</ Pranav >

**Pull request merged**
