### PR TITLE
 Incorporate PRs and Additional Updates

### PR DESCRIPTION
**Pull request by mysport12**
Incorporates PRs #42 (which builds upon #11) and #51 and adds the following

Added prettier config
Updated Example
Updated RNPhotoEditor, simplifying and removing extraneous code
Moved podspec to the root directory
Android build config settings were updated
Listed react-native as a peerDependency
photoEditor.hiddenControls was commented out to avoid a build failure

### CODE REVIEW

**Comment by mysport12** [comment]
Created a PR to update iOSPhotoEditor as well. With the Swift 3.x -> 4.x upgrade some changes are needed in that repo for us Objective C consumers. Here is the link to that PR https://github.com/eventtus/photo-editor/pull/68

**Comment by gsdatta** [comment]
@prscX could we get this merged? also need to bump `pod-installer` version to handle the fixes we merged there recently

**Comment by babakansari** [comment]
The Android related changes in following commit are needed for the latest react-native:
https://github.com/prscX/react-native-photo-editor/pull/54/commits/89fd29465f8f9a2883d3ddbf407c15ebbdf75658
Please merge this PR.

**Comment by Tyldar** [comment]
Hi, @prscX is it possible to merge this one? Everybody needs it

**Comment by ThibaultJRD** [comment]
Hello @prscX, I need this PR too. Could you merge please?

**Comment by prscX** [comment]
Thanks @mysport12 for the Efforts you have added to this PR.

My sincere apologies for the delay. I have merged the same. Post testing, I will push the build.

Thanks
</ Pranav >

**Comment by mehrdadgit** [comment]
Hi all, thanks for your work on this. I have a question: it seems the iOS setup instructions in readme.md is out of date after this merge? any chance we get some hints on how to link the  `master` not `0.0.7`?  Have tried autolinking at https://github.com/react-native-community/cli/blob/master/docs/autolinking.md but no luck on getting a successful build..

**Pull request merged**
