### PR TITLE
Android Crop Feature

### PR DESCRIPTION
**Pull request by RZulfikri**
issue :
https://github.com/prscX/react-native-photo-editor/issues/35
https://github.com/prscX/react-native-photo-editor/issues/32
https://github.com/prscX/react-native-photo-editor/issues/13

update :
add crop feature for android using the same library in react-native-image-crop-picker

### CODE REVIEW

**Comment by RZulfikri** [comment]
@prscX if you have any free time, please check my PR hopefully it can help many people who facing android crop issue. 
thanks.

**Comment by babar7** [comment]
@RZulfikri if you have any solution on my issue please guide me
https://github.com/prscX/react-native-photo-editor/issues/81#issue-488143847

**Comment by babar7** [comment]
@RZulfikri Still facing android crop issue.

**Comment by prscX** [comment]
Thanks @RZulfikri for the Effort and PR.

I have merged the same. Post QA I will push the release.

Thanks,
</ Pranav >

**Pull request merged**
