### PR TITLE
Improvement: iOS: Copy instead of overwriting the orginial file - Android: Callback invoked after finishing editing

### PR DESCRIPTION
**Pull request by tonimoeckel**
Instead of overwriting the original file, I made a change to copy the file in the tmp folder of the iOS device.

### CODE REVIEW

**Comment by tonimoeckel** [comment]
@prscX I'm not sure if this change is that what you expected. I needed this because my file was created in the tmp folder and the lib could not overwrite the file. So I had to create a new one. Thats why I used the callback to send the file path to the react native callback.

**Comment by tonimoeckel** [comment]
HI @prscX ! I also fixed a issue on android devices. At the moment the callback was not invoked on android devices. I added some lines to get the activity result und invoked the callback on result code "OK".

**Comment by prscX** [comment]
Thanks @tonimoeckel for the PR and Effort.

w.r.t `I needed this because my file was created in the tmp folder and the lib could not overwrite the file.` Can you please help me in order to understand the issue. 

If photo is placed in temp iOS storage folder then library is not able to override the file? Initially did you copied the file in temp folder?

Thanks
</ Pranav >

**Comment by prscX** [comment]
Thanks @tonimoeckel for the Effort you have added for this PR.

I have merged [PR: 54](https://github.com/prscX/react-native-photo-editor/pull/54) which contains this PR changes as well. Since the changes are already merged, I am closing this PR.

Thanks
</ Pranav >

**Pull request closed without merging**
