### PR TITLE
Migrate to React native 0.63.2 and typescript

### PR DESCRIPTION
**Pull request by AliRezaBeigy**
Migrate Example to React native 0.63.2
Migrate to typescript
Update gitignore
Fix crash index not found
Remove useless condition to hidden controls

### CODE REVIEW

**Comment by prscX** [comment]
Thanks @AliRezaBeigy for all the efforts you have added.

I have merged the PR. Post validate, I will push the release.

Thanks
</ Pranav >

**Comment by prscX** [comment]
@AliRezaBeigy: I have pushed the [release - 1.0.7](https://github.com/prscX/react-native-photo-editor/releases/tag/v1.0.7).

Please follow updated installation steps defined in README. Let me know incase you face any issues.

Thanks
</ Pranav >

**Comment by AliRezaBeigy** [comment]
https://github.com/prscX/react-native-photo-editor#-usage
this part should update to the following code:

```
import PhotoEditor from 'react-native-photo-editor'

PhotoEditor .Edit({
    path: RNFS.DocumentDirectoryPath + "/photo.jpg"
});
```

**Comment by AliRezaBeigy** [comment]
@prscX 
I have the following error on mac:
```
yarn install v1.22.4
warning package.json: License should be a valid SPDX license expression
info No lockfile found.
warning react-native-photo-editor@1.0.7: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "prettier-pack > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
warning "prettier-pack > eslint-config-prettier@6.10.1" has unmet peer dependency "eslint@>=3.14.1".
warning "prettier-pack > eslint-plugin-prettier@3.1.2" has unmet peer dependency "eslint@>= 5.0.0".
warning "prettier-pack > eslint-plugin-prettier@3.1.2" has unmet peer dependency "prettier@>= 1.13.0".
warning "prettier-pack > eslint-plugin-babel@5.3.0" has unmet peer dependency "eslint@>=4.0.0".
warning "prettier-pack > eslint-plugin-react@7.19.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning "prettier-pack > eslint-plugin-flowtype@4.7.0" has unmet peer dependency "eslint@>=6.1.0".
warning "prettier-pack > eslint-plugin-import@2.20.2" has unmet peer dependency "eslint@2.x - 6.x".
[4/4] 🔨  Building fresh packages...
[-/4] ⠁ waiting...
[4/4] ⠁ prettier-pack
[-/4] ⠁ waiting...
error /Users/arb/IdeaProjects/react-native-photo-editor/node_modules/prettier-pack: Command failed.
Exit code: 127
Command: node script.js && code --install-extension dbaeumer.vscode-eslint && code --install-extension esbenp.prettier-vscode
Arguments: 
Directory: /Users/arb/IdeaProjects/react-native-photo-editor/node_modules/prettier-pack
```

**Comment by prscX** [comment]
Got you. I will look into this and update you.

Thanks

**Comment by AliRezaBeigy** [comment]
@prscX In README Add 'RNRichText' to the static framework in podfile

**Comment by AliRezaBeigy** [comment]
And also remove @type/react from devDependency for the library

**Comment by prscX** [comment]
@AliRezaBeigy: I have pushed a new release [V1.0.8]. Could you please install and verify.

I have removed `RNRichText` from Example, it was by mistake and not needed.

Thanks
</ Pranav >

**Comment by AliRezaBeigy** [comment]
@prscX: everything looks ok in ios and android, now just should update ReadMe as I said in [this comment](https://github.com/prscX/react-native-photo-editor/pull/141#issuecomment-691680765)

**Comment by prscX** [comment]
Done, Thanks.

**Pull request merged**
